set -g status off          # no status bar
set -g mouse on            # mouse scrolling
set -g default-terminal "xterm-256color"
set -g set-titles on       # propagate inner title to outer terminal
set -g set-titles-string '#T'
